#!/usr/bin/env bash

# Checks if an argument is provided
if [ $# -eq 0 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

# Gets the IP address from the argument
ip_address="$1"

ping -c 5 "$ip_address"
