#!/usr/bin/env bash

# Find the process ID (PID) of the 4-to_infinity_and_beyond process
pid=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinate process
if [ -z "$pid" ]; then
  echo "4-to_infinity_and_beyond process is not running."
else
kill "$pid"

  echo "4-to_infinity_and_beyond process with PID $pid has been stopped."
fi
