#!/usr/bin/env bash

#Displays To infinity and beyond indefinitely

#Handle SIGTERM

trap "echo 'I am invincible!!!'" 15

# Infinite loop
while true; do
  echo "To infinity and beyond indefinitely"
  sleep 2
done

