#!/usr/bin/env bash

# Function to handle SIGTERM signal
function handle_sigterm 
{
  echo "I am invincible!!!"
  exit 0
}

# Register the handle_sigterm function to handle SIGTERM
trap handle_sigterm SIGTERM

# Infinite loop
while true; do
  echo "To infinity and beyond indefinitely"
  sleep 2
done

