#!/usr/bin/env bash
# Configure DNS resolution using the custom hosts file
hosts_tmp=~/hosts.new
cp /etc/hosts ~/hosts_tmp
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts_tmp
sed -i "$ a\8.8.8.8 facebook.com" ~/hosts_tmp

cp -f ~/hosts_tmp /etc/hosts
